apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-mongodb-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-gp2
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0f295a2fc8579b743 # 替换为您的EBS卷ID