apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-client
  name: mongo-client
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mongo-client
  type: ClusterIP

