apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-drive-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-drive-server
  template:
    metadata:
      labels:
        app: cloud-drive-server
    spec:
      containers:
      - name: cloud-drive-server
        image: xianxiliang/cloud16:v1
        ports:
        - containerPort: 3001
        env:
        - name: PV_ROOT
          value: "/app/data"
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          # claimName: cloud-drive-pvc
          claimName: aws-cloud-pvc
