apiVersion: v1
kind: ServiceAccount
metadata:
  name: transit-server-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: transit-server-role
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps","pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: transit-server-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: transit-server-sa
roleRef:
  kind: Role
  name: transit-server-role
  apiGroup: rbac.authorization.k8s.io

