apiVersion: apps/v1
kind: Deployment
metadata:
  name: transit-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transit-server
  template:
    metadata:
      labels:
        app: transit-server
    spec:
      serviceAccountName:  transit-server-sa
      containers:
      - name: transit-server
        image: xianxiliang/tran19:v1
        ports:
        - containerPort: 8080
        env:
        - name: POD_ADDRESS_1
          value: "http://ai-agent.default.svc.cluster.local:5000"
        - name: MAX_CONCURRENT_USERS
          value: "50"

